site:
  title: "Meink· 轻量级静态博客构建工具"
  subtitle: "Keep It Simple & Stupid"
  limit: 5
  theme: theme
  language: zh-cn
  logo: "/favicon.ico"
  url: "http://www.jinyan.ink"
  root: "/Meink"
  version: "MEINK 1.0.0(bate)"
  copyright: "你的备案号"
  link: "{year}{month}{day}{hour}{minute}{second}.html"


authors:
  me:
    name: "Meink"
    intro: "Meink"
    avatar: "/author.png"


build:
    output: "public"
    source: "source"
    port: 8080
    copy:
        - "source"
    publish: | # 需要自己设定目录
        scp -r /home/hanjinyan/app/src/Meink/ root@你的服务器ip:/目录

